### ISSUE TITLE
filebrowser-safe installation error

### ISSUE THREAD

**Issue by FelipeGdM** [petedermott/mezzanine#8]
Hello everyone,

I found an error with the dependency filebrowser-safe trying to run the 2.2-compat cfa519b

Installing everything with ```python setup.py install``` goes well, but when I try to run the command ```python manage.py createdb``` I get the following error:

```bash
File ".../venv/lib/python3.6/site-packages/filebrowser_safe-0.5.0-py3.6.egg/filebrowser_safe/views.py", line 14, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

That is a [deprecated syntax](https://stackoverflow.com/questions/43139081/importerror-no-module-named-django-core-urlresolvers) dropped in Django 1.9

It is possible to fix the error installing filebrowser-safe direct from [its repo](https://github.com/stephenmcd/filebrowser-safe). 

The installed version from mezzanine setup.py and from the official repo claims to be 0.5.0, but one is working and the other is not 😝

I don't know the difference from both installation sources, so I writing this issue

**Comment by petedermott** [comment]
Hi,

I'm assuming you are trying to use the 2.2 fork of Mezzanine, correct? If so you should install filebrowser_safe and grapelli_safe forks first via pip with `pip install git+git://github.com/fermorltd/grappelli-safe@2.2-compat` and `pip install git+git://github.com/fermorltd/filebrowser-safe.git@2.2-compat`, then install Mezzanine.

This should skip over the filebrowser_safe dependancy in the `setup.py` file and you should be good to go.

**Comment by FelipeGdM** [comment]
> I'm assuming you are trying to use the 2.2 fork of Mezzanine, correct?  

That's correct

> If so you should install filebrowser_safe and grapelli_safe forks first via pip with `pip install git+git://github.com/fermorltd/grappelli-safe@2.2-compat` and `pip install git+git://github.com/fermorltd/filebrowser-safe.git@2.2-compat`, then install Mezzanine.

Right! Sounds good

Thank you very much!
